#' @title A function for creating consensus between DEA and LASSO
#' @description This function creates a consensus between the results from
#' DEA and LASSO/Elastic net/Ridge regression. Specifically, only the features
#' present in LASSO results are kept in the DEA results table and are sorted
#' based on DEA results.
#' Additionally, a Venn diagram visualizing overlaps is generated.
#' @param DEA.out a data frame from RunDEA containing features and their
#' corresponding AveExpr, logFC, p.value, adj.p.value ect. Mandatory column
#' is "name"
#' @param LASSO.results an object generated by runLASSO function
#' @param group a factor specifying group for each sample (e.g. could be represented by a column from a metadata file)
#' @param viridis.palette a character vector specifying color gradient to use for
#' the heatmap. Default option for viridis color palettes is 'turbo'. For more
#' options, see viridis vignette.
#' @param prefix a character string defining a prefix of output file.
#' @export
#' @import VennDiagram
#' @return
#' 1) a data frame of features common for both DEA and LASSO which are extracted
#' from DEAout table
#' 2) a .png with a Venn diagram of features' intersections between DEA and LASSO
#' @examples {
#' campp2_brca_1_DEA_LASSO_consensus <- RunDEA_LASSO_consensus(
#'     campp2_brca_1_DEA$DEA.out,
#'     campp2_brca_1_LASSO, group=campp2_brca_1_meta$diagnosis,
#'    viridis.palette="turbo", "test")
#' }


RunDEA_LASSO_consensus<-function(DEA.out, LASSO.results, group, viridis.palette="turbo", prefix){
    consensus <- DEA.out[DEA.out$name %in% LASSO.results$VarsSelect[,1],]  ##list is sorted based on logFC in DEA.out

    if (nrow(consensus) > 0) {
        pdf(paste0(prefix, "_overlap_DEA_LASSO.pdf"), height=8, width=12)
        if (length(levels(group)) == 2) {
            venn <- venn.diagram(list(A=unique(as.character(DEA.out[DEA.out$dir =="up.reg",]$name)), B=unique(as.character(DEA.out[DEA.out$dir =="down.reg",]$name)), C=as.character(LASSO.results$VarsSelect[,1])), category.names = c("DEA Analysis Up", "DEA Analysis Down", "LASSO/EN/Ridge Regression"), filename=NULL, lwd = 0.7, cat.pos=0, sub.cex = 2, cat.cex= 1.5, cex=1.5, fill=viridis(3, begin = 0.2, end = 0.8, option=viridis.palette))
        } else {
            venn <- venn.diagram(list(A=unique(as.character(DEA.out$name)), B=as.character(LASSO.results$VarsSelect[,1])), category.names = c("DEA output", "LASSO/EN/Ridge regression output"), filename=NULL, lwd = 0.7, cat.pos=0, sub.cex = 2, cat.cex= 1.5, cex=1.5, fill=viridis(2, begin = 0.2, end = 0.8, option=viridis.palette))
        }
        grid.draw(venn)
        dev.off()
    } else {
        cat("There is no consensus between LASSO/EN/Ridge regression and DEA in dataset.")
    }
    return(consensus)
}
