#' @title RunHeatmap
#' @description A function for making heatmaps to showcase the difference in
#' expression/abundance of features across samples and sample groups and to
#' visualise relations between them.
#' @param feature.counts a feature count matrix (ideally normalized and batch
#' corrected) generated by "seq", "array", "ms" or "other" technology (with
#' feature IDs as row names and sample IDs as columns). It's recommended to
#' import feature counts using function "import_counts".
#' @param DEA.out.heatmap a sorted data frame representing output from one of:
#' 1) runDEA which is based on the output format from limma.
#' Data frame sorted e.g. by logFC. Mandatory column is "name".
#' 2) runLASSO (including feature names)
#' 3) consensus of DEA and LASSO/EN/Ridge regression generated by
#' RunDEA_LASSO_consensus and and including features sorted based on DEA
#' logFC values). Mandatory column is "name".
#' @param heatmap.size an argument specifying how many genes will be selected
#' to be plotted on the heatmap if plot.heatmap is TRUE. The input must be
#' specified as an even number. Default is 30.
#'
#' Please, consider that some of the TOP DEA features might be present multiple
#' times in the DEA output due to the multiple groups comparisons.
#' On the heatmap, each feature will be projected only once so the final number
#' of the projected features migh by lower then heatmap.size.
#' @param group a factor specifying group for each sample (e.g. could be
#' represented by a column from a metadata file). Group's information
#' will be used in clustering the samples.
#' @param viridis.palette a character vector specifying color gradient to use for
#' the heatmap. Default option for viridis color palettes is 'turbo'. For more
#' options, see viridis vignette.
#' @param plot.heatmap an argument defining which data will be used for
#' the selection of the top x features to be plotted on the heatmap.
#' Options are:"DEA", "LASSO", "EN", "Ridge" or "Consensus".
#' @param prefix a character vector defining prefix of output file name.
#' @param data.type a character vector for labeling units in the legend.
#' Default is "expression/abundance".
#' @export
#' @import ComplexHeatmap
#' @import squash
#' @import viridisLite
#' @import grid
#' @return heatmap
#' @examples {
#' RunHeatmap(campp2_brca_1_batchCorrected, campp2_brca_1_DEA_HUGO, 40,
#' campp2_brca_1_meta$subtype, viridis.palette="turbo",
#' plot.heatmap="DEA", "test_heatmap")
#' }

RunHeatmap<-function(feature.counts, DEA.out.heatmap, heatmap.size=30, group, viridis.palette="turbo", plot.heatmap="DEA", prefix, data.type="expression/abundance"){

    if(plot.heatmap == "DEA"){
        DEA.out.heatmap <- rbind(head(DEA.out.heatmap,heatmap.size/2),tail(DEA.out.heatmap,heatmap.size/2))  ##Select top x DEA features from the top/bottom for the sorted DEA output
        DEA.out.heatmap.name <- DEA.out.heatmap$name
        DEA.out.heatmap <- unique(DEA.out.heatmap.name)
        if(length(DEA.out.heatmap) < heatmap.size){
            heatmap.size <- length(DEA.out.heatmap)
            print(paste0("heatmap.size is reduced to ", heatmap.size))
        }
        prefix<-paste0(prefix,"_",plot.heatmap)
        feature.counts <- feature.counts[rownames(feature.counts) %in% DEA.out.heatmap,]
        print(paste0("Top ", heatmap.size, " DEA features will be selected for heatplot. Signifficant features are represented by 1/2 of upregulated features and 1/2 of downregulated features. Please, consider that some of the TOP DEA features might be present multiple times in the DEA output due to the multiple groups comparisons - on the heatmap each feature will be projected only once so the final number for projected features migh by lower then heatmap.size. "))
        print(paste0("Number of duplicates in the top ", heatmap.size, " DEA features is: ", (length(DEA.out.heatmap)-length(unique((DEA.out.heatmap))))))
    } else if (plot.heatmap =="Consensus"){
        DEA.out.heatmap <- rbind(head(as.character(DEA.out.heatmap$name),heatmap.size/2),tail(as.character(DEA.out.heatmap$name),heatmap.size/2))  ##Select top x DEA features from the top/bottom for the sorted DEA output
        DEA.out.heatmap <- unique(DEA.out.heatmap)
        if(length(DEA.out.heatmap) < heatmap.size){
            heatmap.size <- length(DEA.out.heatmap)
            print(paste0("heatmap.size is reduced to ", heatmap.size))
        }
        prefix<-paste0(prefix,"_",plot.heatmap)
        feature.counts <- feature.counts[rownames(feature.counts) %in% DEA.out.heatmap,]
        print(paste0("Top ", heatmap.size, " consensual (DEA vs LASSO/EN/Ridge) features are selected for the heatplot. Consensual features are sorted based on their logFC values from the DEA output including all the comparisons. The selection includes 1/2 of the upregulated features (logFC) and 1/2 of the downregulated features."))

    } else if (plot.heatmap %in% c("EN", "LASSO", "Ridge")){  ##Here it's difficult to sort the features based on their significance as they are generated based on an intersection of several (10) LASSO runs
        DEA.out.heatmap <- rbind(head(DEA.out.heatmap$VarsSelect[,1],heatmap.size/2),tail(DEA.out.heatmap$VarsSelect[,1],heatmap.size/2))  ##Select top x DEA features from the top/bottom for the sorted DEA output
        DEA.out.heatmap <- unique(DEA.out.heatmap)
        if(length(DEA.out.heatmap) < heatmap.size){
            heatmap.size <- length(DEA.out.heatmap)
            print(paste0("heatmap.size is reduced to ", heatmap.size), " due to the insufficient number of the features.")
        }
        prefix<-paste0(prefix,"_",plot.heatmap)
        feature.counts <- feature.counts[rownames(feature.counts) %in% DEA.out.heatmap,]
        print("Currently, features from EN/LASSO/Ridge regression are not sorted based on their coefficients. This should be considered while setting heatmap.size parameter which should ideally cover all the features to avoid removal of any significant feature.")
    } else {
        stop(paste0("plot.heatmap value ", plot.heatmap, " is not supported. Supported values are: DEA, Consensus, EN, LASSO and Ridge."))
    }


    # Heatmap as pdf
    MakeHeatmap(feature.counts, group, prefix, viridis.palette, data.type)  ##"Feature counts" might become optional

}
